// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from WorldObjectTemplate.tt />

namespace Eco.Mods.TechTree
{
    using Eco.Gameplay.Objects;
	using CavRn.StorageControl;

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class AshlarBasaltFireplaceObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class AshlarGneissFireplaceObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class AshlarGraniteFireplaceObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class AshlarLimestoneFireplaceObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class AshlarSandstoneFireplaceObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class AshlarShaleFireplaceObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class AshlarStoneFireplaceObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class BakeryOvenObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class BlastFurnaceObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class BloomeryObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class BookshelfObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class BrazierObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class BrickFireplaceObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class CampfireObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class CampsiteObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class CandleStandObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class CarvedPumpkinObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class CastIronStoveObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class CeilingCandleObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class CementKilnObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class CombustionGeneratorObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class CompositeLumberDresserObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class CrabPotObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class DistributionStationObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class FishTrapObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class GlassworksObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class HardwoodLumberDresserObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class HewnDresserObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class IceboxObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class IndustrialGeneratorObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class IndustrialRefrigeratorObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class KilnObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class LargeLumberStockpileObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class LumberDresserObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class LumberStockpileObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class MortaredGraniteFireplaceObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class MortaredLimestoneFireplaceObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class MortaredSandstoneFireplaceObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class MortaredStoneFireplaceObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class OilRefineryObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class OutpostNettingObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class PaintMixerObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class PlanterPotRoundObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class PlanterPotSquareObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class PlasticWindowPlanterObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class PoweredStorageSiloObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class RefrigeratorObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class RusticWindowPlanterObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class ShelfCabinetObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class SmallStockpileObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class SoftwoodLumberDresserObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class SteamEngineObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class SteelWarehouseShelvesObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class StockpileObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class StoneBrazierObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class StorageChestObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class StorageSiloObject
    {
    }

	[RequireComponent(typeof(StorageControlComponent))]
	public partial class TallowCandleObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class TallowLampObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class TallowWallLampObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class TikiTorchObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class TinyStockpileObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class TorchStandObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class WallCandleObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class WallMountedChestObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class WallMountedTrunkObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class WoodWindowPlanterObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class WoodenWallTorchStandObject
    {
    }

	// Vehicles

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class CraneObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class EgyptianCanoeObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class ExcavatorObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class IndustrialBargeObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class LargeCanoeObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class MediumFishingTrawlerObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class NorseCanoeObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class PoweredCartObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class SkidSteerObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class SmallCanoeObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class SmallWoodCartObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class SmallWoodenBoatObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class SteamTractorObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class SteamTruckObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class TrailerTruckObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class TruckObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class WheelbarrowObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class WoodCartObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class WoodShopCartObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class WoodenBargeObject
    {
    }

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class WoodenTransportShipObject
    {
    }
}
