// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from WorldObjectTemplate.tt />

namespace Eco.Mods.TechTree
{
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
	using CavRn.StorageControl;

    [RequireComponent(typeof(StorageControlComponent))]
	public partial class StockpileObject : WorldObject, IRepresentsItem
    {
    }
}
